-- =============================================================================
-- LAWNLENS: match_plants Postgres RPC (pgvector Cosine Similarity Search)
-- =============================================================================
-- File: supabase/migrations/20260228_match_plants_rpc.sql
--
-- PURPOSE:
--   This migration creates the core backend function used to power the RAG
--   (Retrieval-Augmented Generation) pipeline for LawnLens plant recommendations.
--
-- HOW IT WORKS:
--   1. The client app (or a Supabase Edge Function) generates a 1536-dimension
--      vector embedding of the user's yard profile using the Dedalus Embeddings API.
--   2. That query embedding is passed into this function.
--   3. Postgres uses the `pgvector` extension to compute the cosine distance
--      between the query vector and every plant's stored embedding vector.
--   4. The function returns the top K most similar plants, sorted by relevance.
--
-- SETUP REQUIREMENTS:
--   - The `vector` extension (pgvector) must be enabled in your Supabase project.
--     Go to: Supabase Dashboard -> Database -> Extensions -> Enable "vector".
--   - The `rag_plants` table must exist with an `embedding vector(1536)` column.
--
-- HOW TO RUN:
--   Option A (Supabase CLI): `supabase db push`
--   Option B (Dashboard):    Copy-paste this file into the Supabase SQL Editor and click Run.
--
-- HOW TO CALL FROM EDGE FUNCTION (TypeScript):
--   const { data, error } = await supabase.rpc('match_plants', {
--     query_embedding: [...1536 floats...],
--     match_threshold: 0.75,
--     match_count: 5
--   })
-- =============================================================================

-- Step 1: Ensure the pgvector extension is active.
-- This is idempotent -- it's safe to run even if it's already enabled.
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Add an IVFFlat index on the embedding column to massively speed up
-- vector similarity searches when the table grows to thousands of rows.
-- IVFFlat (Inverted File with Flat quantization) is the recommended pgvector
-- index type for tables with >10,000 rows. `lists` = sqrt(number of rows),
-- starting with 100 lists is a safe default for tables of up to ~10,000 rows.
-- NOTE: This index only needs to be created once. The IF NOT EXISTS guard is added
-- to make this entire migration safely re-runnable.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'rag_plants_embedding_idx'
  ) THEN
    CREATE INDEX rag_plants_embedding_idx
      ON rag_plants
      USING ivfflat (embedding vector_cosine_ops)
      WITH (lists = 100);
  END IF;
END
$$;

-- Step 3: Create (or replace) the core `match_plants` RPC function.
-- Using `CREATE OR REPLACE` makes this migration idempotent.
CREATE OR REPLACE FUNCTION match_plants(
  -- The 1536-dimensional vector embedding for the user's yard profile/query.
  -- This is generated by the Dedalus Embedding API and passed in from the Edge Function.
  query_embedding VECTOR(1536),

  -- Minimum cosine similarity score required to include a plant in results.
  -- Range: 0.0 (completely different) to 1.0 (identical).
  -- A threshold of 0.75 means the plant must be at least 75% similar to the query.
  -- Lower this to get more (but less relevant) results. Raise to get fewer (but more precise).
  match_threshold FLOAT DEFAULT 0.75,

  -- The maximum number of plants to return. Typically 5-10 for an LLM context window.
  match_count INT DEFAULT 5
)
-- Returns a table (set of rows) so it can be consumed like a SELECT statement.
RETURNS TABLE (
  id             UUID,
  common_name    TEXT,
  scientific_name TEXT,
  description    TEXT,
  sun_requirements TEXT[],
  water_requirement TEXT,
  min_hardiness_zone INT,
  max_hardiness_zone INT,
  mature_height_meters FLOAT,
  is_toxic_to_pets BOOLEAN,
  is_invasive      BOOLEAN,
  landscape_uses   TEXT,
  native_regions   TEXT[],
  -- The cosine similarity score (0.0 to 1.0). Higher = more relevant.
  -- Not stored in the table, computed on the fly by this function.
  similarity       FLOAT
)
LANGUAGE SQL
-- STABLE means this function does not modify the database and returns the same
-- result for the same inputs within a single transaction. This allows Postgres
-- to optimize repeated calls efficiently.
STABLE
AS $$
  SELECT
    p.id,
    p.common_name,
    p.scientific_name,
    p.description,
    p.sun_requirements,
    p.water_requirement,
    p.min_hardiness_zone,
    p.max_hardiness_zone,
    p.mature_height_meters,
    p.is_toxic_to_pets,
    p.is_invasive,
    p.landscape_uses,
    p.native_regions,
    -- 1 - cosine_distance gives us cosine SIMILARITY (higher = more similar).
    -- The `<=>` operator is pgvector's built-in cosine distance operator.
    1 - (p.embedding <=> query_embedding) AS similarity
  FROM
    rag_plants p
  WHERE
    -- Pre-filter out plants below the similarity threshold BEFORE sorting.
    -- This dramatically reduces the work Postgres has to do, especially with
    -- the IVFFlat index active.
    1 - (p.embedding <=> query_embedding) > match_threshold
  ORDER BY
    -- Sort by most similar first so the calling function gets best results at index [0].
    p.embedding <=> query_embedding ASC
  LIMIT
    -- Cap the results to avoid overwhelming the LLM context window.
    match_count;
$$;

-- =============================================================================
-- GRANT PERMISSIONS:
-- Allow the `anon` role (used by unauthenticated clients) and `authenticated`
-- role (logged-in users) to execute this function. Without this, Supabase will
-- block the call with a permissions error even from within an Edge Function
-- that uses the service role client.
-- =============================================================================
GRANT EXECUTE ON FUNCTION match_plants(VECTOR(1536), FLOAT, INT)
  TO anon, authenticated;
